#!/bin/dash -f

for i in "'' grow" "Control- grow -1" "Shift- nudge"; do
                eval "set -- $i"; mod=$1; cmd=$2; shift 2
                #cat 's/^            /'  "
        "            Key Escape
                            exit
                    Key $mod-LEFT
                            wmiir xwrite /tag/sel/ctl $cmd sel sel left $*
                    Key $mod-RIGHT
                            wmiir xwrite /tag/sel/ctl $cmd sel sel right $*
                    Key $mod-UP
                            wmiir xwrite /tag/sel/ctl $cmd sel sel up $*
                    Key $mod-DOWN
                            wmiir xwrite /tag/sel/ctl $cmd sel sel down $*
        "
done

