#!/bin/dash -f
# <h/j/k/l>  moves the window in the given direction
# C-<h/j/k/l> grows the window in the given direction
# S-<h/j/k/l> shrinks the window in the given direction

wmoderesize() {
	{ 
	   echo Escape
	   echo Control-$LEFT
	   echo Control-$RIGHT
	   echo Control-$UP
	   echo Control-$DOWN
	   echo Shift-$LEFT
	   echo Shift-$RIGHT
	   echo Shift-$UP
	   echo Shift-$DOWN
	   echo $RIGHT
	   echo $LEFT
	   echo $UP
	   echo $DOWN
	} | wmiir write /keys
	# Turn off globbing
	set -f
	wmiir read /event |
	while read line; do
	     set -- $line
	     event=$1;shift
	     line = "$(echo $line )"  #| sed 's/^[^ ]* //' | tr -d '\n')"
	     case $event in
	     Key)
		case $1 in
		    Escape) echo -n "$Keys" | wmiir write /keys ; break ;;
                    Control-$LEFT) wmiir xwrite /tag/sel/ctl grow sel sel left ;;
		    Control-$RIGHT) wmiir xwrite /tag/sel/ctl grow sel sel right ;;
		    Control-$UP) wmiir xwrite /tag/sel/ctl grow sel sel up ;;
		    Control-$DOWN) wmiir xwrite /tag/sel/ctl grow sel sel down ;;
		    Shift-$LEFT) wmiir xwrite /tag/sel/ctl grow sel sel left -1 ;;
		    Shift-$RIGHT) wmiir xwrite /tag/sel/ctl grow sel sel right -1 ;;
	            Shift-$UP) wmiir xwrite /tag/sel/ctl grow sel sel up -1 ;;
	 	    Shift-$DOWN)  wmiir xwrite /tag/sel/ctl grow sel sel down -1 ;;
		    $LEFT) wmiir xwrite /tag/sel/ctl nudge sel sel left ;;
		    $RIGHT) wmiir xwrite /tag/sel/ctl nudge sel sel right ;;
		    $UP) wmiir xwrite /tag/sel/ctl nudge sel sel up ;;
		    $DOWN) wmiir xwrite /tag/sel/ctl nudge sel sel down ;;
	        esac;;
	    esac
	done
}

wi_events <<'!'
Key $MODKEY-Control-r
	wmoderesize &
!

